use super::ColorRgba;

/// OpenXR extension name for Meta/Facebook compositor passthrough.
pub const XR_FB_PASSTHROUGH_EXTENSION: &str = "XR_FB_passthrough";

/// OpenXR extension name for app-defined triangle meshes used by projected passthrough.
pub const XR_FB_TRIANGLE_MESH_EXTENSION: &str = "XR_FB_triangle_mesh";

/// OpenXR extension name for 3D passthrough color LUTs.
pub const XR_META_PASSTHROUGH_COLOR_LUT_EXTENSION: &str = "XR_META_passthrough_color_lut";

/// Number of entries required by the `XR_FB_passthrough` mono color-map structs.
pub const PASSTHROUGH_COLOR_MAP_SIZE: usize = 256;

/// How a native compositor passthrough layer should be generated by the runtime.
///
/// This mirrors the public OpenXR layer-purpose vocabulary. It is a descriptor,
/// not a platform handle.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum PassthroughLayerPurpose {
    /// Runtime-reconstructed full-environment passthrough.
    #[default]
    Reconstruction,
    /// Passthrough projected onto app-supplied geometry.
    Projected,
    /// Runtime-tracked keyboard hands passthrough, where supported.
    TrackedKeyboardHands,
    /// Runtime-tracked keyboard hands with keyboard-masked hand transitions.
    TrackedKeyboardMaskedHands,
}

impl PassthroughLayerPurpose {
    pub const fn stable_id(self) -> &'static str {
        match self {
            Self::Reconstruction => "reconstruction",
            Self::Projected => "projected",
            Self::TrackedKeyboardHands => "tracked-keyboard-hands",
            Self::TrackedKeyboardMaskedHands => "tracked-keyboard-masked-hands",
        }
    }

    pub const fn openxr_name(self) -> &'static str {
        match self {
            Self::Reconstruction => "XR_PASSTHROUGH_LAYER_PURPOSE_RECONSTRUCTION_FB",
            Self::Projected => "XR_PASSTHROUGH_LAYER_PURPOSE_PROJECTED_FB",
            Self::TrackedKeyboardHands => "XR_PASSTHROUGH_LAYER_PURPOSE_TRACKED_KEYBOARD_HANDS_FB",
            Self::TrackedKeyboardMaskedHands => {
                "XR_PASSTHROUGH_LAYER_PURPOSE_TRACKED_KEYBOARD_MASKED_HANDS_FB"
            }
        }
    }

    pub const fn needs_projection_mesh(self) -> bool {
        matches!(self, Self::Projected)
    }
}

/// Where the passthrough proxy layer should sit relative to the app projection layer.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum PassthroughLayerPlacement {
    /// Submit before the main projection layer so virtual content appears on top.
    #[default]
    Underlay,
    /// Submit after the main projection layer so passthrough can cover virtual content.
    Overlay,
}

impl PassthroughLayerPlacement {
    pub const fn stable_id(self) -> &'static str {
        match self {
            Self::Underlay => "underlay",
            Self::Overlay => "overlay",
        }
    }
}

/// Extension requirements implied by a public passthrough descriptor.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PassthroughExtensionRequirements {
    pub fb_passthrough: bool,
    pub fb_triangle_mesh: bool,
    pub meta_passthrough_color_lut: bool,
}

impl PassthroughExtensionRequirements {
    pub const FB_PASSTHROUGH: Self = Self {
        fb_passthrough: true,
        fb_triangle_mesh: false,
        meta_passthrough_color_lut: false,
    };

    pub const fn merge(self, other: Self) -> Self {
        Self {
            fb_passthrough: self.fb_passthrough || other.fb_passthrough,
            fb_triangle_mesh: self.fb_triangle_mesh || other.fb_triangle_mesh,
            meta_passthrough_color_lut: self.meta_passthrough_color_lut
                || other.meta_passthrough_color_lut,
        }
    }

    pub fn extension_names(self) -> Vec<&'static str> {
        let mut names = Vec::new();
        if self.fb_passthrough {
            names.push(XR_FB_PASSTHROUGH_EXTENSION);
        }
        if self.fb_triangle_mesh {
            names.push(XR_FB_TRIANGLE_MESH_EXTENSION);
        }
        if self.meta_passthrough_color_lut {
            names.push(XR_META_PASSTHROUGH_COLOR_LUT_EXTENSION);
        }
        names
    }
}

/// Native compositor passthrough layer descriptor.
///
/// Apps still need a platform adapter to create OpenXR handles, submit a proxy
/// `XrCompositionLayerPassthroughFB`, and keep the platform session alive.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, PartialEq)]
pub struct PlatformPassthroughLayer {
    pub purpose: PassthroughLayerPurpose,
    pub placement: PassthroughLayerPlacement,
    pub style: PassthroughStyle,
    pub running_at_creation: bool,
    pub blend_source_alpha: bool,
}

impl PlatformPassthroughLayer {
    pub const fn new(purpose: PassthroughLayerPurpose) -> Self {
        Self {
            purpose,
            placement: PassthroughLayerPlacement::Underlay,
            style: PassthroughStyle::NEUTRAL,
            running_at_creation: true,
            blend_source_alpha: true,
        }
    }

    pub const fn reconstruction_underlay() -> Self {
        Self::new(PassthroughLayerPurpose::Reconstruction)
    }

    pub const fn with_placement(mut self, placement: PassthroughLayerPlacement) -> Self {
        self.placement = placement;
        self
    }

    pub fn with_style(mut self, style: PassthroughStyle) -> Self {
        self.style = style;
        self
    }

    pub const fn with_running_at_creation(mut self, running_at_creation: bool) -> Self {
        self.running_at_creation = running_at_creation;
        self
    }

    pub const fn with_blend_source_alpha(mut self, blend_source_alpha: bool) -> Self {
        self.blend_source_alpha = blend_source_alpha;
        self
    }

    pub fn is_valid(&self) -> bool {
        self.style.is_valid()
    }

    pub fn extension_requirements(&self) -> PassthroughExtensionRequirements {
        let mut requirements = PassthroughExtensionRequirements::FB_PASSTHROUGH;
        if self.purpose.needs_projection_mesh() {
            requirements.fb_triangle_mesh = true;
        }
        requirements.merge(self.style.extension_requirements())
    }
}

impl Default for PlatformPassthroughLayer {
    fn default() -> Self {
        Self::reconstruction_underlay()
    }
}

/// Style parameters for a native compositor passthrough layer.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, PartialEq)]
pub struct PassthroughStyle {
    pub texture_opacity_factor: f32,
    pub edge_color: ColorRgba,
    pub color_reproduction: PassthroughColorReproduction,
}

impl PassthroughStyle {
    pub const NEUTRAL: Self = Self {
        texture_opacity_factor: 1.0,
        edge_color: ColorRgba::new(0.0, 0.0, 0.0, 0.0),
        color_reproduction: PassthroughColorReproduction::None,
    };

    pub const fn with_texture_opacity_factor(mut self, texture_opacity_factor: f32) -> Self {
        self.texture_opacity_factor = texture_opacity_factor;
        self
    }

    pub const fn with_edge_color(mut self, edge_color: ColorRgba) -> Self {
        self.edge_color = edge_color;
        self
    }

    pub fn with_color_reproduction(
        mut self,
        color_reproduction: PassthroughColorReproduction,
    ) -> Self {
        self.color_reproduction = color_reproduction;
        self
    }

    pub fn is_valid(&self) -> bool {
        unit(self.texture_opacity_factor)
            && color_is_unit(self.edge_color)
            && self.color_reproduction.is_valid()
    }

    pub fn edge_rendering_enabled(&self) -> bool {
        self.edge_color.a > 0.0
    }

    pub fn extension_requirements(&self) -> PassthroughExtensionRequirements {
        self.color_reproduction.extension_requirements()
    }
}

impl Default for PassthroughStyle {
    fn default() -> Self {
        Self::NEUTRAL
    }
}

/// Mutually exclusive color reproduction mode for `XrPassthroughStyleFB`.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, Default, PartialEq)]
pub enum PassthroughColorReproduction {
    /// Keep the runtime's native passthrough colors.
    #[default]
    None,
    /// Convert luminance to another 8-bit luminance value.
    MonoToMono(PassthroughMonoToMonoMap),
    /// Convert luminance to RGBA through a 256-entry color map.
    MonoToRgba(PassthroughMonoToRgbaMap),
    /// Adjust brightness, contrast, and saturation in the runtime style path.
    BrightnessContrastSaturation(PassthroughColorAdjustment),
    /// Apply a runtime-created 3D color LUT.
    ColorLut(PassthroughColorLutBinding),
    /// Interpolate between two runtime-created 3D color LUTs.
    InterpolatedColorLut(PassthroughInterpolatedColorLutBinding),
}

impl PassthroughColorReproduction {
    pub fn stable_id(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::MonoToMono(_) => "mono-to-mono",
            Self::MonoToRgba(_) => "mono-to-rgba",
            Self::BrightnessContrastSaturation(_) => "brightness-contrast-saturation",
            Self::ColorLut(_) => "color-lut",
            Self::InterpolatedColorLut(_) => "interpolated-color-lut",
        }
    }

    pub fn is_valid(&self) -> bool {
        match self {
            Self::None => true,
            Self::MonoToMono(map) => map.is_valid(),
            Self::MonoToRgba(map) => map.is_valid(),
            Self::BrightnessContrastSaturation(adjustment) => adjustment.is_valid(),
            Self::ColorLut(binding) => binding.is_valid(),
            Self::InterpolatedColorLut(binding) => binding.is_valid(),
        }
    }

    pub fn extension_requirements(&self) -> PassthroughExtensionRequirements {
        match self {
            Self::ColorLut(_) | Self::InterpolatedColorLut(_) => PassthroughExtensionRequirements {
                fb_passthrough: true,
                fb_triangle_mesh: false,
                meta_passthrough_color_lut: true,
            },
            _ => PassthroughExtensionRequirements::FB_PASSTHROUGH,
        }
    }
}

/// Brightness, contrast, and saturation adjustment for passthrough layers.
#[repr(C)]
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PassthroughColorAdjustment {
    pub brightness: f32,
    pub contrast: f32,
    pub saturation: f32,
}

impl PassthroughColorAdjustment {
    pub const NEUTRAL: Self = Self {
        brightness: 0.0,
        contrast: 1.0,
        saturation: 1.0,
    };

    pub const fn new(brightness: f32, contrast: f32, saturation: f32) -> Self {
        Self {
            brightness,
            contrast,
            saturation,
        }
    }

    pub fn is_valid(self) -> bool {
        finite_range(self.brightness, -100.0, 100.0)
            && self.contrast.is_finite()
            && self.contrast >= 0.0
            && self.saturation.is_finite()
            && self.saturation >= 0.0
    }

    pub fn is_neutral(self) -> bool {
        self == Self::NEUTRAL
    }
}

impl Default for PassthroughColorAdjustment {
    fn default() -> Self {
        Self::NEUTRAL
    }
}

/// A monotonic gradient stop used to build public 256-entry passthrough maps.
#[repr(C)]
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct PassthroughGradientStop {
    pub position: f32,
    pub color: ColorRgba,
}

impl PassthroughGradientStop {
    pub const fn new(position: f32, color: ColorRgba) -> Self {
        Self { position, color }
    }

    pub fn is_valid(self) -> bool {
        unit(self.position) && color_is_unit(self.color)
    }
}

/// Fixed 256-entry mono-to-mono passthrough color map.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PassthroughMonoToMonoMap {
    pub entries: Vec<u8>,
}

impl PassthroughMonoToMonoMap {
    pub fn identity() -> Self {
        let entries = (0..PASSTHROUGH_COLOR_MAP_SIZE)
            .map(|index| index as u8)
            .collect();
        Self { entries }
    }

    pub fn inverted() -> Self {
        let entries = (0..PASSTHROUGH_COLOR_MAP_SIZE)
            .map(|index| u8::MAX - index as u8)
            .collect();
        Self { entries }
    }

    pub fn is_valid(&self) -> bool {
        self.entries.len() == PASSTHROUGH_COLOR_MAP_SIZE
    }
}

impl Default for PassthroughMonoToMonoMap {
    fn default() -> Self {
        Self::identity()
    }
}

/// Fixed 256-entry mono-to-RGBA passthrough color map.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, PartialEq)]
pub struct PassthroughMonoToRgbaMap {
    pub entries: Vec<ColorRgba>,
}

impl PassthroughMonoToRgbaMap {
    pub fn grayscale_identity() -> Self {
        let entries = (0..PASSTHROUGH_COLOR_MAP_SIZE)
            .map(|index| {
                let luminance = index as f32 / (PASSTHROUGH_COLOR_MAP_SIZE - 1) as f32;
                ColorRgba::new(luminance, luminance, luminance, 1.0)
            })
            .collect();
        Self { entries }
    }

    pub fn from_gradient(stops: &[PassthroughGradientStop]) -> Option<Self> {
        if !gradient_is_valid(stops) {
            return None;
        }

        let entries = (0..PASSTHROUGH_COLOR_MAP_SIZE)
            .map(|index| {
                let position = index as f32 / (PASSTHROUGH_COLOR_MAP_SIZE - 1) as f32;
                sample_gradient(position, stops)
            })
            .collect();
        Some(Self { entries })
    }

    pub fn from_wrapped_gradient(stops: &[PassthroughGradientStop], phase01: f32) -> Option<Self> {
        if !gradient_is_valid(stops) || !phase01.is_finite() {
            return None;
        }

        let entries = (0..PASSTHROUGH_COLOR_MAP_SIZE)
            .map(|index| {
                let position = (index as f32 / (PASSTHROUGH_COLOR_MAP_SIZE - 1) as f32 + phase01)
                    .rem_euclid(1.0);
                sample_gradient(position, stops)
            })
            .collect();
        Some(Self { entries })
    }

    pub fn is_valid(&self) -> bool {
        self.entries.len() == PASSTHROUGH_COLOR_MAP_SIZE
            && self.entries.iter().copied().all(color_is_unit)
    }
}

impl Default for PassthroughMonoToRgbaMap {
    fn default() -> Self {
        Self::grayscale_identity()
    }
}

/// Channel shape for `XR_META_passthrough_color_lut` data.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum PassthroughColorLutChannels {
    #[default]
    Rgb,
    Rgba,
}

impl PassthroughColorLutChannels {
    pub const fn bytes_per_element(self) -> usize {
        match self {
            Self::Rgb => 3,
            Self::Rgba => 4,
        }
    }
}

/// Public descriptor for a 3D passthrough color LUT.
#[repr(C)]
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PassthroughColorLutSpec {
    pub channels: PassthroughColorLutChannels,
    pub resolution: u32,
}

impl PassthroughColorLutSpec {
    pub const fn new(channels: PassthroughColorLutChannels, resolution: u32) -> Self {
        Self {
            channels,
            resolution,
        }
    }

    pub fn buffer_size_bytes(self) -> Option<usize> {
        let resolution = usize::try_from(self.resolution).ok()?;
        resolution
            .checked_mul(resolution)?
            .checked_mul(resolution)?
            .checked_mul(self.channels.bytes_per_element())
    }

    pub fn is_valid(self) -> bool {
        self.resolution > 0
            && self.resolution.is_power_of_two()
            && self.buffer_size_bytes().is_some()
    }

    pub fn fits_max_resolution(self, max_resolution: u32) -> bool {
        self.is_valid() && max_resolution >= self.resolution
    }
}

impl Default for PassthroughColorLutSpec {
    fn default() -> Self {
        Self::new(PassthroughColorLutChannels::Rgb, 32)
    }
}

/// Reference to a runtime-created passthrough color LUT handle.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, PartialEq)]
pub struct PassthroughColorLutBinding {
    pub lut_id: String,
    pub weight: f32,
}

impl PassthroughColorLutBinding {
    pub fn new(lut_id: impl Into<String>, weight: f32) -> Self {
        Self {
            lut_id: lut_id.into(),
            weight,
        }
    }

    pub fn is_valid(&self) -> bool {
        !self.lut_id.trim().is_empty() && unit(self.weight)
    }
}

/// Reference to two runtime-created passthrough LUT handles and an interpolation weight.
#[cfg_attr(feature = "serde", derive(serde::Deserialize, serde::Serialize))]
#[derive(Clone, Debug, PartialEq)]
pub struct PassthroughInterpolatedColorLutBinding {
    pub source_lut_id: String,
    pub target_lut_id: String,
    pub weight: f32,
}

impl PassthroughInterpolatedColorLutBinding {
    pub fn new(
        source_lut_id: impl Into<String>,
        target_lut_id: impl Into<String>,
        weight: f32,
    ) -> Self {
        Self {
            source_lut_id: source_lut_id.into(),
            target_lut_id: target_lut_id.into(),
            weight,
        }
    }

    pub fn is_valid(&self) -> bool {
        !self.source_lut_id.trim().is_empty()
            && !self.target_lut_id.trim().is_empty()
            && self.source_lut_id != self.target_lut_id
            && unit(self.weight)
    }
}

/// Build a generic audio-reactive mono-to-RGBA style from a phase and amplitude.
///
/// This helper intentionally models only the public pattern: audio controls
/// the phase of a luminance color map and the alpha of edge rendering.
pub fn audio_reactive_mono_to_rgba_style(
    phase01: f32,
    amplitude01: f32,
    gradient: &[PassthroughGradientStop],
) -> Option<PassthroughStyle> {
    if !phase01.is_finite() || !unit(amplitude01) {
        return None;
    }

    let map = PassthroughMonoToRgbaMap::from_wrapped_gradient(gradient, phase01)?;
    let edge_alpha = amplitude01.sqrt().clamp(0.0, 1.0) * 0.85;
    let edge_rgb = mix_color(
        ColorRgba::new(0.15, 0.35, 0.95, 1.0),
        ColorRgba::new(0.95, 0.90, 0.20, 1.0),
        amplitude01,
    );
    let edge_color = ColorRgba::new(edge_rgb.r, edge_rgb.g, edge_rgb.b, edge_alpha);

    Some(
        PassthroughStyle::NEUTRAL
            .with_edge_color(edge_color)
            .with_color_reproduction(PassthroughColorReproduction::MonoToRgba(map)),
    )
}

fn gradient_is_valid(stops: &[PassthroughGradientStop]) -> bool {
    if stops.len() < 2 || !stops.iter().copied().all(PassthroughGradientStop::is_valid) {
        return false;
    }

    stops
        .windows(2)
        .all(|pair| pair[0].position <= pair[1].position)
}

fn sample_gradient(position: f32, stops: &[PassthroughGradientStop]) -> ColorRgba {
    let position = position.clamp(0.0, 1.0);
    if position <= stops[0].position {
        return stops[0].color;
    }

    for pair in stops.windows(2) {
        let left = pair[0];
        let right = pair[1];
        if position <= right.position {
            let span = (right.position - left.position).max(f32::EPSILON);
            let amount = ((position - left.position) / span).clamp(0.0, 1.0);
            return mix_color(left.color, right.color, amount);
        }
    }

    stops[stops.len() - 1].color
}

fn mix_color(left: ColorRgba, right: ColorRgba, amount: f32) -> ColorRgba {
    let amount = amount.clamp(0.0, 1.0);
    let inverse = 1.0 - amount;
    ColorRgba::new(
        left.r * inverse + right.r * amount,
        left.g * inverse + right.g * amount,
        left.b * inverse + right.b * amount,
        left.a * inverse + right.a * amount,
    )
}

fn color_is_unit(color: ColorRgba) -> bool {
    unit(color.r) && unit(color.g) && unit(color.b) && unit(color.a)
}

fn unit(value: f32) -> bool {
    finite_range(value, 0.0, 1.0)
}

fn finite_range(value: f32, min: f32, max: f32) -> bool {
    value.is_finite() && (min..=max).contains(&value)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn near(actual: f32, expected: f32) {
        assert!(
            (actual - expected).abs() < 1.0e-5,
            "expected {expected}, got {actual}"
        );
    }

    fn public_gradient() -> Vec<PassthroughGradientStop> {
        vec![
            PassthroughGradientStop::new(0.0, ColorRgba::new(0.02, 0.02, 0.08, 1.0)),
            PassthroughGradientStop::new(0.5, ColorRgba::new(0.15, 0.70, 0.95, 1.0)),
            PassthroughGradientStop::new(1.0, ColorRgba::new(0.95, 0.85, 0.20, 1.0)),
        ]
    }

    #[test]
    fn neutral_reconstruction_underlay_is_valid() {
        let layer = PlatformPassthroughLayer::reconstruction_underlay();

        assert!(layer.is_valid());
        assert_eq!(
            layer.purpose.openxr_name(),
            "XR_PASSTHROUGH_LAYER_PURPOSE_RECONSTRUCTION_FB"
        );
        assert_eq!(
            layer.extension_requirements().extension_names(),
            vec![XR_FB_PASSTHROUGH_EXTENSION]
        );
    }

    #[test]
    fn projected_layer_requires_triangle_mesh_extension() {
        let layer = PlatformPassthroughLayer::new(PassthroughLayerPurpose::Projected);

        assert!(layer.is_valid());
        assert_eq!(
            layer.extension_requirements().extension_names(),
            vec![XR_FB_PASSTHROUGH_EXTENSION, XR_FB_TRIANGLE_MESH_EXTENSION]
        );
    }

    #[test]
    fn mono_to_rgba_gradient_builds_256_entries() {
        let map = PassthroughMonoToRgbaMap::from_gradient(&public_gradient())
            .expect("gradient should build");

        assert!(map.is_valid());
        assert_eq!(map.entries.len(), PASSTHROUGH_COLOR_MAP_SIZE);
        near(map.entries[0].r, 0.02);
        near(map.entries[255].b, 0.20);
    }

    #[test]
    fn color_adjustment_validates_openxr_ranges() {
        assert!(PassthroughColorAdjustment::NEUTRAL.is_valid());
        assert!(PassthroughColorAdjustment::new(-100.0, 0.0, 0.0).is_valid());
        assert!(!PassthroughColorAdjustment::new(-101.0, 1.0, 1.0).is_valid());
        assert!(!PassthroughColorAdjustment::new(0.0, -0.1, 1.0).is_valid());
    }

    #[test]
    fn lut_spec_reports_required_buffer_size() {
        let spec = PassthroughColorLutSpec::new(PassthroughColorLutChannels::Rgba, 32);

        assert!(spec.is_valid());
        assert_eq!(spec.buffer_size_bytes(), Some(32 * 32 * 32 * 4));
        assert!(spec.fits_max_resolution(32));
        assert!(!spec.fits_max_resolution(16));
        assert!(!PassthroughColorLutSpec::new(PassthroughColorLutChannels::Rgb, 30).is_valid());
    }

    #[test]
    fn lut_style_requires_meta_lut_extension() {
        let style = PassthroughStyle::NEUTRAL.with_color_reproduction(
            PassthroughColorReproduction::ColorLut(PassthroughColorLutBinding::new(
                "warm-grade",
                0.6,
            )),
        );

        assert!(style.is_valid());
        assert_eq!(
            style.extension_requirements().extension_names(),
            vec![
                XR_FB_PASSTHROUGH_EXTENSION,
                XR_META_PASSTHROUGH_COLOR_LUT_EXTENSION
            ]
        );
    }

    #[test]
    fn audio_reactive_style_phase_shifts_gradient_and_edges() {
        let style = audio_reactive_mono_to_rgba_style(0.25, 0.64, &public_gradient())
            .expect("audio style should build");

        assert!(style.is_valid());
        assert!(style.edge_rendering_enabled());
        near(style.edge_color.a, 0.68);
        assert_eq!(style.color_reproduction.stable_id(), "mono-to-rgba");
    }

    #[cfg(feature = "serde")]
    #[test]
    fn passthrough_layer_round_trips_with_serde() {
        let style = PassthroughStyle::NEUTRAL.with_color_reproduction(
            PassthroughColorReproduction::BrightnessContrastSaturation(
                PassthroughColorAdjustment::new(4.0, 1.1, 0.8),
            ),
        );
        let layer = PlatformPassthroughLayer::reconstruction_underlay().with_style(style);

        let encoded = serde_json::to_string(&layer).expect("layer should serialize");
        let decoded: PlatformPassthroughLayer =
            serde_json::from_str(&encoded).expect("layer should deserialize");

        assert_eq!(decoded, layer);
    }
}
