"""Argument-surface defaults for companion session routes."""

from __future__ import annotations


DEFAULT_COMPANION_SESSION_WAIT_SECONDS = 30.0
DEFAULT_COMPANION_SESSION_AUTHORITY_WAIT_SECONDS = 30.0
DEFAULT_COMPANION_SESSION_PROCESS_WAIT_SECONDS = 20.0
DEFAULT_COMPANION_SESSION_SOCKET_WAIT_SECONDS = 20.0
DEFAULT_COMPANION_SESSION_LAUNCH_SETTLE_SECONDS = 8.0
DEFAULT_COMPANION_SESSION_RUNTIME_SUBSCRIBER_RETRY_COUNT = 8
DEFAULT_COMPANION_SESSION_RUNTIME_SUBSCRIBER_RETRY_WAIT_SECONDS = 2.0
