"""Compatibility facade for Quest connectivity lab data-protocol adapters."""

from __future__ import annotations

from tools.hostessctl.connectivity_data_protocols_common import (
    parse_probe_json_stdout,
    protocol_topology_checks,
    shell_quote,
)
from tools.hostessctl.connectivity_data_protocols_lsl import (
    live_lsl_report,
    lsl_checks_from_probe,
    lsl_discovery_sample_continuity,
    lsl_manifold_broker_probe,
    lsl_quest_runtime_preflight,
    lsl_quest_runtime_report_from_file,
    resolve_lsl_manifold_root,
)
from tools.hostessctl.connectivity_data_protocols_osc import (
    DEFAULT_QCL083_OSC_PORT,
    build_osc_message,
    live_osc_report,
    osc_checks_from_probe,
    osc_loopback_probe,
    osc_quest_runtime_payload_probe,
    osc_string,
    parse_osc_message,
    qcl083_remote_evidence_path,
    read_osc_string,
    run_qcl083_android_osc_probe,
)
from tools.hostessctl.connectivity_data_protocols_zeromq import (
    DEFAULT_QCL084_ZEROMQ_PORT,
    live_zeromq_report,
    parse_native_zmq_loopback_stdout,
    parse_rusty_xr_zmq_loopback_stdout,
    resolve_goofi_bridge_root,
    resolve_manifold_root,
    resolve_qcl084_probe_binary,
    resolve_rusty_xr_root,
    run_qcl084_android_zeromq_probe,
    zeromq_blocked_result,
    zeromq_checks_from_probe,
    zeromq_goofi_sidecar_probe,
    zeromq_loopback_probe,
    zeromq_manifold_broker_probe,
    zeromq_manifold_loopback_probe,
    zeromq_rusty_xr_loopback_probe,
)

__all__ = [
    "DEFAULT_QCL083_OSC_PORT",
    "DEFAULT_QCL084_ZEROMQ_PORT",
    "build_osc_message",
    "live_lsl_report",
    "live_osc_report",
    "live_zeromq_report",
    "lsl_checks_from_probe",
    "lsl_discovery_sample_continuity",
    "lsl_manifold_broker_probe",
    "lsl_quest_runtime_preflight",
    "lsl_quest_runtime_report_from_file",
    "osc_checks_from_probe",
    "osc_loopback_probe",
    "osc_quest_runtime_payload_probe",
    "osc_string",
    "parse_native_zmq_loopback_stdout",
    "parse_osc_message",
    "parse_probe_json_stdout",
    "parse_rusty_xr_zmq_loopback_stdout",
    "protocol_topology_checks",
    "qcl083_remote_evidence_path",
    "read_osc_string",
    "resolve_goofi_bridge_root",
    "resolve_lsl_manifold_root",
    "resolve_manifold_root",
    "resolve_qcl084_probe_binary",
    "resolve_rusty_xr_root",
    "run_qcl083_android_osc_probe",
    "run_qcl084_android_zeromq_probe",
    "shell_quote",
    "zeromq_blocked_result",
    "zeromq_checks_from_probe",
    "zeromq_goofi_sidecar_probe",
    "zeromq_loopback_probe",
    "zeromq_manifold_broker_probe",
    "zeromq_manifold_loopback_probe",
    "zeromq_rusty_xr_loopback_probe",
]
